# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159t0Oq2T-tsCppYXz_w4obB3qZqv3OXp
"""

import glob, os
import numpy as np
from PIL import Image
from IPython import display
import matplotlib.pyplot as plt
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import torch
import torch.nn as nn
from torch.autograd import Variable
from torchvision import datasets, transforms

googleColaboratory = True
entrenamiento = True
convolucionProfunda = False
resNet = True
if googleColaboratory:
    import google as goo

lote_size = 4

# Entrenamiento
if googleColaboratory:
    trainset = datasets.CIFAR10('/content/drive/My Drive/Colab Notebooks/data/', download=True, train=True, transform=transforms.ToTensor())
else:
    trainset = datasets.CIFAR10('data/', download=True, train=True, transform=transforms.ToTensor())
trainloader = torch.utils.data.DataLoader(trainset, batch_size=lote_size, shuffle=True)

if googleColaboratory:
    testset = datasets.CIFAR10('/content/drive/My Drive/Colab Notebooks/data/', download=True, train=False, transform=transforms.ToTensor())
else:
    testset = datasets.CIFAR10('data/', download=True, train=False, transform=transforms.ToTensor())
testloader = torch.utils.data.DataLoader(testset, batch_size=lote_size, shuffle=True)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=lote_size, shuffle=True)

# Prueba
testset = datasets.CIFAR10('data/', download=True, train=False, transform=transforms.ToTensor())
testloader = torch.utils.data.DataLoader(testset, batch_size=lote_size, shuffle=True)

print("Tensor Entrenamiento=", trainset.data.shape, "Tensor Validación=", testset.data.shape)
clases = ('avion', 'coche', 'pajaro', 'gato', 'ciervo', 'perro', 'rana', 'caballo', 'barco', 'camión')

from torchvision.utils import make_grid
for ix in range(3):
  for images, _ in trainloader:
    plt.figure(figsize=(6,3))
    plt.axis('off')
    plt.imshow(make_grid(images, nrow=16).permute((1, 2, 0)))
    break

class CNN_short(nn.Module):
    def __init__(self):
        super(CNN_short, self).__init__()
        # capa convolucional (ve tensores Nx3x32x32 y devuelve tensores Nx6x28x28)
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=6, kernel_size=5, stride=1, padding=0)
        self.pool = nn.MaxPool2d(kernel_size=2)   # Devuelve tensores  Nx6x14x14

        # capa convolucional (ve tensores Nx6x14x14  y devuelve tensores Nx16x10x10)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=16, kernel_size=5, stride=1, padding=0)
        # Capa oculta totalmente conectada. Salida a 10 clases

        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x))) # Entran tensores Nx3x32x32 y salen Nx6x14x14
        x = self.pool(F.relu(self.conv2(x))) # Entran tensores Nx6x14x14 y salen Nx16x5x5
        # Se aplana la salida de conv2 a (batch_size, 16 * 5 * 5)
        #x = x.view(x.size(0), -1)
        x = x.view(-1, 16*5*5) # Se aplana a un vector 16x5x5 = 400
        x = F.relu(self.fc1(x)) # Capa densa de 400 -> 120
        #x = F.dropout(x, 0.5) #dropout se incluye para evitar overfitting
        x = F.relu(self.fc2(x)) # Capa densa de 120 -> 84
        #x = F.dropout(x, 0.5) #dropout se incluye para evitar overfitting
        x = self.fc3(x) # Capa densa de 84 -> 10 con la puntuación por clase
        return x

class CNN_long(nn.Module):
  def __init__(self):
        super().__init__()
        self.network = nn.Sequential(
            nn.Conv2d(3, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2), # salida: N x 16 x 16 x 64

            nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2), # salida: N x 8 x 8 x 128

            nn.Conv2d(128, 256, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.Conv2d(256, 256, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2), # salida: N x 4 x 4 x 256

            nn.Flatten(), # Se aplana a un vector 4 x 4 x 256 = 4096
            nn.Linear(256*4*4, 1024), # Red densa FC : De 4096 -> 1024
            nn.ReLU(),
            nn.Linear(1024, 512),  # Red densa FC : De 1024 -> 512
            nn.ReLU(),
            nn.Linear(512, 10))  # Red densa FC : De 512 -> 10 con la puntuación por clase

  def forward(self, xb):
        return self.network(xb)

# 3x3 convolution
def conv3x3(in_channels, out_channels, stride=1):
    return nn.Conv2d(in_channels, out_channels, kernel_size=3,
                     stride=stride, padding=1, bias=False)

# Residual block
class ResidualBlock(nn.Module):
    def __init__(self, in_channels, out_channels, stride=1, downsample=None):
        super(ResidualBlock, self).__init__()
        self.conv1 = conv3x3(in_channels, out_channels, stride)
        self.bn1 = nn.BatchNorm2d(out_channels)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = conv3x3(out_channels, out_channels)
        self.bn2 = nn.BatchNorm2d(out_channels)
        self.downsample = downsample

    def forward(self, x):
        residual = x
        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)
        out = self.conv2(out)
        out = self.bn2(out)
        if self.downsample:
            residual = self.downsample(x)
        out += residual
        out = self.relu(out)
        return out

# ResNet
class ResNet(nn.Module):
    def __init__(self, block, layers, num_classes=10):
        super(ResNet, self).__init__()
        self.in_channels = 16
        self.conv = conv3x3(3, 16)
        self.bn = nn.BatchNorm2d(16)
        self.relu = nn.ReLU(inplace=True)
        self.layer1 = self.make_layer(block, 16, layers[0])
        self.layer2 = self.make_layer(block, 32, layers[1], 2)
        self.layer3 = self.make_layer(block, 64, layers[2], 2)
        self.avg_pool = nn.AvgPool2d(8)
        self.fc = nn.Linear(64, num_classes)

    def make_layer(self, block, out_channels, blocks, stride=1):
        downsample = None
        if (stride != 1) or (self.in_channels != out_channels):
            downsample = nn.Sequential(
                conv3x3(self.in_channels, out_channels, stride=stride),
                nn.BatchNorm2d(out_channels))
        layers = []
        layers.append(block(self.in_channels, out_channels, stride, downsample))
        self.in_channels = out_channels
        for i in range(1, blocks):
            layers.append(block(out_channels, out_channels))
        return nn.Sequential(*layers)

    def forward(self, x):
        out = self.conv(x)
        out = self.bn(out)
        out = self.relu(out)
        out = self.layer1(out)
        out = self.layer2(out)
        out = self.layer3(out)
        out = self.avg_pool(out)
        out = out.view(out.size(0), -1)
        out = self.fc(out)
        return out

# Se crea un modelo CNN
#if googleColaboratory:
if googleColaboratory:
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu') #training with either cpu or cuda

if resNet:
    if googleColaboratory:
      model = ResNet(ResidualBlock, [2, 2, 2]).to(device)
    else:
        model = ResNet(ResidualBlock, [2, 2, 2])
elif convolucionProfunda:
  model = CNN_long()
else:
  model = CNN_short()
if googleColaboratory:
  model = model.to(device=device) #to send the model for training on either cuda or cpu

print(model)

import torch.optim as optim

# Se especifica la función pérdida
loss_func = nn.CrossEntropyLoss()

# Se especifica el optimizador
optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)
#optimizer = optim.Adam(model.parameters(), lr=0.001)

from torch.autograd import Variable
num_epochs = 10
model.train()

lineasTraza = int(len(trainloader)/20)+1
numlineas = 0
# Train the model
for epoch in range(num_epochs):
    if not entrenamiento:
      print("No habilitada la opción de entrenamiento")
      break
    correct = 0
    total = 0
    for images, labels in trainloader:
        images = images.to(device=device)
        labels = labels.to(device=device)

        # gives batch data, normalize x when iterate train_loader
        b_x = Variable(images)   # batch x
        b_y = Variable(labels)   # batch y
        output = model(b_x)
        loss = loss_func(output, b_y)
        pred_y = torch.max(output, 1)[1].data.squeeze()
        correct += (pred_y == labels).sum().item()
        total +=float(labels.size(0))
        # clear gradients for this training step
        optimizer.zero_grad()

        # backpropagation, compute gradients
        loss.backward()
        # apply gradients
        optimizer.step()
        numlineas+=1
        if numlineas == lineasTraza:
            print('*', end='')
            numlineas=0

    print ('Época [{}], Accuracy-Entrenamiento {:.4f}'.format(epoch + 1, 100*correct/total))

filename = "cifar10_profunda.pt" if convolucionProfunda else "cifar10_short.pt"
if resNet: filename = "cifar10_resnet.pt"
filename = "/content/drive/My Drive/Colab Notebooks/data/" + filename if googleColaboratory else "data/" + filename
if entrenamiento:
    print("Backup al fichero=", filename)
    torch.save(model.state_dict(), filename)
    if googleColaboratory:
      goo.colab.files.download(filename)
else:
    print("No habilitado Backup del fichero")

model = model.to(device)

filename = "/content/drive/My Drive/Colab Notebooks/data/" + filename if googleColaboratory else "data/" + filename
print("Fichero cargado=", filename)
if not entrenamiento:
  if googleColaboratory:
    model.load_state_dict(torch.load(filename, map_location=torch.device('cpu'))) #recovery trained model
  else:
    model.load_state_dict(torch.load(filename, map_location=torch.device('cpu'))) #recovery trained model
  model.eval()
  print(model)

model.eval()
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in testloader:
        images = images.to(device=device)
        labels = labels.to(device=device)
        test_output = model(Variable(images))
        pred_y = torch.max(test_output, 1)[1].data.squeeze()
        #accuracy = (pred_y == labels).sum().item() / float(labels.size(0))
        correct += (pred_y == labels).sum().item()
        total +=float(labels.size(0))
    accuracy=100*correct/total
print('El Acierto en los 10.000 ejemplos de prueba es : %.2f %%' % accuracy)

import matplotlib.pyplot as plt
lote_image, lote_label = next(iter(testloader))
if resNet:
  lote_mapa1 = model.conv(lote_image)
  lote_mapa2 = model.bn(lote_mapa1)
  lote_mapa3 = model.relu(lote_mapa2)
  lote_mapa4 = model.layer1[0].conv1(lote_mapa3)
  lote_mapa5 = model.layer1[0].bn1(lote_mapa4)
  lote_mapa6 = model.layer1[0].relu(lote_mapa5)
  lote_mapa7 = model.layer1[0].conv2(lote_mapa6)
  lote_mapa8 = model.layer1[0].bn2(lote_mapa7)
  lote_mapa9 = model.layer1[1].conv1(lote_mapa8)
  lote_mapa10 = model.layer1[1].bn1(lote_mapa9)
  lote_mapa11 = model.layer1[1].relu(lote_mapa10)
  lote_mapa12 = model.layer1[1].conv2(lote_mapa11)
  lote_mapa13 = model.layer1[1].bn2(lote_mapa12)
  lote_mapa14 = model.layer2[0].conv1(lote_mapa13)
  lote_mapa15 = model.layer2[0].bn1(lote_mapa14)
elif convolucionProfunda:
  conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
  lote_mapa1 = conv1(lote_image)
  lote_mapa2 = F.relu(lote_mapa1)
  conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
  lote_mapa3 = conv2(lote_mapa2)
  lote_mapa4 = F.relu(lote_mapa3)
  pool = nn.MaxPool2d(2, 2)
  lote_mapa5 = pool(lote_mapa4)
  conv3 = nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1)
  lote_mapa6 = conv3(lote_mapa5)
  lote_mapa7 = F.relu(lote_mapa6)
  conv4 = nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=1)
  lote_mapa8 = conv4(lote_mapa7)
  lote_mapa9 = F.relu(lote_mapa8)
  lote_mapa10 = pool(lote_mapa9)
  conv5 = nn.Conv2d(128, 256, kernel_size=3, stride=1, padding=1)
  lote_mapa11 = conv5(lote_mapa10)
  lote_mapa12 = F.relu(lote_mapa11)
  conv6 = nn.Conv2d(256, 256, kernel_size=3, stride=1, padding=1)
  lote_mapa13 = conv6(lote_mapa12)
  lote_mapa14 = F.relu(lote_mapa13)
  lote_mapa15 = pool(lote_mapa14)
else:
  lote_mapa1 = model.conv1(lote_image)
  lote_mapa2 = F.relu(lote_mapa1)
  lote_mapa3 = model.pool(lote_mapa2)
  lote_mapa4 = model.conv2(lote_mapa3)
  lote_mapa5 = F.relu(lote_mapa4)
  lote_mapa6 = model.pool(lote_mapa5)
image = lote_image[0]  ## Se coge la primera imagen del lote
mapa1 = lote_mapa1[0]
mapa2 = lote_mapa2[0]
mapa3 = lote_mapa3[0]
mapa4 = lote_mapa4[0]
mapa5 = lote_mapa5[0]
mapa6 = lote_mapa6[0]
if convolucionProfunda or resNet:
  mapa7 = lote_mapa7[0]
  mapa8 = lote_mapa8[0]
  mapa9 = lote_mapa9[0]
  mapa10 = lote_mapa10[0]
  mapa11 = lote_mapa11[0]
  mapa12 = lote_mapa12[0]
  mapa13 = lote_mapa13[0]
  mapa14 = lote_mapa14[0]
  mapa15 = lote_mapa15[0]
label = int(lote_label[0])
numCols = 16 if convolucionProfunda or resNet else 7
fig, ax = plt.subplots(nrows=10, ncols=numCols, figsize=(18,14))
#ax = ax.flatten()
if resNet:
  literales=['Imagen', 'Conv', 'Normal', 'ReLU', 'Conv', 'Normal', 'ReLU', 'Conv', 'Normal', 'Conv', 'Normal', 'ReLU', 'Conv', 'Normal', 'Conv', 'Normal', 'ReLU']
elif convolucionProfunda:
  literales=['Imagen', 'Conv1', 'ReLU', 'Conv2', 'ReLU', 'Pool', 'Conv3', 'ReLU', 'Conv4', 'ReLU', 'Pool', 'Conv5', 'ReLU', 'Conv6', 'ReLU', 'Pool']
else:
  literales=['Imagen', 'Conv1', 'ReLU', 'Pool', 'Conv2', 'ReLU', 'Pool']
for i in range(10):
    ax[i][0].imshow(image.numpy().transpose((1, 2, 0)))
    if i < mapa1.shape[0]:
        ax[i][1].imshow(mapa1[i].detach().numpy())
        ax[i][2].imshow(mapa2[i].detach().numpy())
        ax[i][3].imshow(mapa3[i].detach().numpy())
    ax[i][4].imshow(mapa4[i].detach().numpy())
    ax[i][5].imshow(mapa5[i].detach().numpy())
    ax[i][6].imshow(mapa6[i].detach().numpy())
    if convolucionProfunda or resNet:
      ax[i][7].imshow(mapa7[i].detach().numpy())
      ax[i][8].imshow(mapa8[i].detach().numpy())
      ax[i][9].imshow(mapa9[i].detach().numpy())
      ax[i][10].imshow(mapa10[i].detach().numpy())
      ax[i][11].imshow(mapa11[i].detach().numpy())
      ax[i][12].imshow(mapa12[i].detach().numpy())
      ax[i][13].imshow(mapa13[i].detach().numpy())
      ax[i][14].imshow(mapa14[i].detach().numpy())
      ax[i][15].imshow(mapa15[i].detach().numpy())
    for j in range(numCols):
        ax[i][j].set_yticks([])
        ax[i][j].set_xticks([])
        ax[0][j].set_title(literales[j])

#fig.suptitle('Imagen tipo ' + str(clases[label]), fontsize=16)
plt.tight_layout()
plt.show()

b_x = Variable(lote_image)   # batch x
output = model(b_x)
fig, (ax1, ax2) = plt.subplots( ncols=2)
y=output[0].detach().numpy()
y = (y - min(y))/(max(y)-min(y))
ax2.axis('off')
ax2.imshow(image.numpy().transpose((1, 2, 0)))
ax1.set_yticks(np.arange(10))
ax1.barh(np.arange(10), y)
ax1.set_yticklabels(clases)
ax1.set_title('Probabilidad')
plt.tight_layout()

def importImagesFromPath(my_directory, imageSize):
    transform = transforms.Compose([
        transforms.Resize(imageSize),
        transforms.CenterCrop(imageSize),
        transforms.ToTensor(),
        transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
        ])
    _first=True
    filesName = []
    for file in glob.glob(my_directory+"/*.jpg"):
        PILimag = Image.open(file)
        tensorImag = transform(PILimag).unsqueeze(0) ## Se transforma en tensor y se añade 1 dimensión
        filesName.append(file)
        if _first:
            loteImag = tensorImag
            _first = False
        else:
            loteImag = torch.cat((loteImag, tensorImag), 0)
    return loteImag, filesName

imagAnimal, filesName = importImagesFromPath("./data/animalsTest", 32)
b_x = Variable(imagAnimal)   # batch x
predict = model(b_x)

iTest=8
fig, (ax1, ax2) = plt.subplots( ncols=2)
y=predict[iTest].detach().numpy()
y = (y - min(y))/(max(y)-min(y))
ax2.axis('off')
ax2.imshow(imagAnimal[iTest].numpy().transpose((1, 2, 0)))
ax2.set_title(filesName[iTest])
ax1.set_title('Probabilidad')
ax1.set_yticks(np.arange(10))
ax1.barh(np.arange(10), y)
ax1.set_yticklabels(clases)
plt.tight_layout()